# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(420, 330, 101, 21))
        self.exit.setObjectName("exit")
        self.coalSorts = QtWidgets.QComboBox(self.centralwidget)
        self.coalSorts.setGeometry(QtCore.QRect(80, 280, 131, 21))
        self.coalSorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.coalSorts.setObjectName("coalSorts")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 59, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 59, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 280, 59, 16))
        self.label_3.setObjectName("label_3")
        self.finishButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishButton.setGeometry(QtCore.QRect(200, 390, 101, 21))
        self.finishButton.setObjectName("finishButton")
        self.priceInput = QtWidgets.QTextEdit(self.centralwidget)
        self.priceInput.setGeometry(QtCore.QRect(80, 310, 104, 21))
        self.priceInput.setObjectName("priceInput")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 310, 59, 16))
        self.label_4.setObjectName("label_4")
        self.startCalender = QtWidgets.QCalendarWidget(self.centralwidget)
        self.startCalender.setGeometry(QtCore.QRect(80, 20, 296, 71))
        self.startCalender.setMinimumSize(QtCore.QSize(296, 0))
        self.startCalender.setObjectName("startCalender")
        self.endCalender = QtWidgets.QCalendarWidget(self.centralwidget)
        self.endCalender.setGeometry(QtCore.QRect(80, 110, 271, 61))
        self.endCalender.setObjectName("endCalender")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(80, 210, 70, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 214, 54, 12))
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(80, 240, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 244, 54, 12))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 23))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuff = QtWidgets.QMenu(self.menu)
        self.menuff.setObjectName("menuff")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menuother = QtWidgets.QMenu(self.menubar)
        self.menuother.setObjectName("menuother")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionedit1 = QtWidgets.QAction(MainWindow)
        self.actionedit1.setObjectName("actionedit1")
        self.actionrr = QtWidgets.QAction(MainWindow)
        self.actionrr.setObjectName("actionrr")
        self.actionkk = QtWidgets.QAction(MainWindow)
        self.actionkk.setObjectName("actionkk")
        self.actionmeizhong = QtWidgets.QAction(MainWindow)
        self.actionmeizhong.setObjectName("actionmeizhong")
        self.actionff_2 = QtWidgets.QAction(MainWindow)
        self.actionff_2.setObjectName("actionff_2")
        self.manage_ticket = QtWidgets.QAction(MainWindow)
        self.manage_ticket.setCheckable(True)
        self.manage_ticket.setObjectName("manage_ticket")
        self.query_ticket_info = QtWidgets.QAction(MainWindow)
        self.query_ticket_info.setObjectName("query_ticket_info")
        self.menuEdit.addAction(self.actionrr)
        self.menuEdit.addAction(self.actionkk)
        self.menuhelp.addSeparator()
        self.menuhelp.addSeparator()
        self.menuff.addAction(self.actionff_2)
        self.menu.addAction(self.menuff.menuAction())
        self.menu_2.addAction(self.manage_ticket)
        self.menu_2.addAction(self.query_ticket_info)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menuother.menuAction())

        self.retranslateUi(MainWindow)
        self.coalSorts.currentIndexChanged['int'].connect(MainWindow.onCoalSortSelected)
        self.exit.clicked.connect(MainWindow.exit)
        self.startCalender.clicked['QDate'].connect(MainWindow.beginDate)
        self.endCalender.clicked['QDate'].connect(MainWindow.endDate)
        self.priceInput.textChanged.connect(MainWindow.getPrice)
        self.finishButton.clicked.connect(MainWindow.onAddFinished)
        self.manage_ticket.triggered.connect(MainWindow.manage_ticket)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.label.setText(_translate("MainWindow", "起始日期"))
        self.label_2.setText(_translate("MainWindow", "截止日期"))
        self.label_3.setText(_translate("MainWindow", "煤种"))
        self.finishButton.setText(_translate("MainWindow", "生成参数表"))
        self.label_4.setText(_translate("MainWindow", "单价"))
        self.label_5.setText(_translate("MainWindow", "日期"))
        self.label_6.setText(_translate("MainWindow", "吨位"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuhelp.setTitle(_translate("MainWindow", "Help"))
        self.menu.setTitle(_translate("MainWindow", "煤种"))
        self.menuff.setTitle(_translate("MainWindow", "ff"))
        self.menu_2.setTitle(_translate("MainWindow", "票种"))
        self.menuother.setTitle(_translate("MainWindow", "other"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionedit1.setText(_translate("MainWindow", "edit1"))
        self.actionrr.setText(_translate("MainWindow", "rr"))
        self.actionrr.setToolTip(_translate("MainWindow", "<html><head/><body><p>rrnihi</p></body></html>"))
        self.actionrr.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionkk.setText(_translate("MainWindow", "kk"))
        self.actionmeizhong.setText(_translate("MainWindow", "meizhong"))
        self.actionff_2.setText(_translate("MainWindow", "ff"))
        self.manage_ticket.setText(_translate("MainWindow", "管理票种"))
        self.manage_ticket.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.query_ticket_info.setText(_translate("MainWindow", "查询票种"))

