# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(390, 510, 101, 21))
        self.exit.setObjectName("exit")
        self.coal_sorts = QtWidgets.QComboBox(self.centralwidget)
        self.coal_sorts.setGeometry(QtCore.QRect(60, 280, 131, 21))
        self.coal_sorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.coal_sorts.setObjectName("coal_sorts")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setGeometry(QtCore.QRect(20, 20, 59, 16))
        self.date_label.setObjectName("date_label")
        self.label_coal = QtWidgets.QLabel(self.centralwidget)
        self.label_coal.setGeometry(QtCore.QRect(10, 280, 59, 16))
        self.label_coal.setObjectName("label_coal")
        self.finishButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishButton.setGeometry(QtCore.QRect(530, 510, 101, 21))
        self.finishButton.setObjectName("finishButton")
        self.date_calender = QtWidgets.QCalendarWidget(self.centralwidget)
        self.date_calender.setGeometry(QtCore.QRect(80, 20, 296, 151))
        self.date_calender.setMinimumSize(QtCore.QSize(296, 0))
        self.date_calender.setObjectName("date_calender")
        self.weight_content = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.weight_content.setGeometry(QtCore.QRect(60, 320, 62, 22))
        self.weight_content.setObjectName("weight_content")
        self.weight_label = QtWidgets.QLabel(self.centralwidget)
        self.weight_label.setGeometry(QtCore.QRect(10, 330, 54, 12))
        self.weight_label.setObjectName("weight_label")
        self.ticket_sorts = QtWidgets.QComboBox(self.centralwidget)
        self.ticket_sorts.setGeometry(QtCore.QRect(60, 370, 131, 21))
        self.ticket_sorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.ticket_sorts.setObjectName("ticket_sorts")
        self.label_ticket = QtWidgets.QLabel(self.centralwidget)
        self.label_ticket.setGeometry(QtCore.QRect(10, 370, 59, 16))
        self.label_ticket.setObjectName("label_ticket")
        self.user_name_label = QtWidgets.QLabel(self.centralwidget)
        self.user_name_label.setGeometry(QtCore.QRect(10, 200, 54, 12))
        self.user_name_label.setObjectName("user_name_label")
        self.user_name_content = QtWidgets.QTextEdit(self.centralwidget)
        self.user_name_content.setGeometry(QtCore.QRect(80, 200, 101, 21))
        self.user_name_content.setObjectName("user_name_content")
        self.car_id_label = QtWidgets.QLabel(self.centralwidget)
        self.car_id_label.setGeometry(QtCore.QRect(10, 240, 54, 16))
        self.car_id_label.setObjectName("car_id_label")
        self.car_id_content = QtWidgets.QTextEdit(self.centralwidget)
        self.car_id_content.setGeometry(QtCore.QRect(80, 240, 101, 21))
        self.car_id_content.setObjectName("car_id_content")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 510, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 23))
        self.menubar.setObjectName("menubar")
        self.edit = QtWidgets.QMenu(self.menubar)
        self.edit.setObjectName("edit")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        self.coal = QtWidgets.QMenu(self.menubar)
        self.coal.setObjectName("coal")
        self.ticket = QtWidgets.QMenu(self.menubar)
        self.ticket.setObjectName("ticket")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.manage_ticket = QtWidgets.QAction(MainWindow)
        self.manage_ticket.setCheckable(True)
        self.manage_ticket.setObjectName("manage_ticket")
        self.query_ticket_info = QtWidgets.QAction(MainWindow)
        self.query_ticket_info.setObjectName("query_ticket_info")
        self.coalManagement = QtWidgets.QAction(MainWindow)
        self.coalManagement.setObjectName("coalManagement")
        self.menuhelp.addSeparator()
        self.menuhelp.addSeparator()
        self.coal.addAction(self.coalManagement)
        self.ticket.addAction(self.manage_ticket)
        self.ticket.addAction(self.query_ticket_info)
        self.menubar.addAction(self.edit.menuAction())
        self.menubar.addAction(self.coal.menuAction())
        self.menubar.addAction(self.ticket.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        self.coal_sorts.currentIndexChanged['int'].connect(MainWindow.onCoalSortSelected)
        self.exit.clicked.connect(MainWindow.exit)
        self.date_calender.clicked['QDate'].connect(MainWindow.beginDate)
        self.finishButton.clicked.connect(MainWindow.onAddFinished)
        self.manage_ticket.triggered.connect(MainWindow.manage_ticket)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.date_label.setText(_translate("MainWindow", "日期"))
        self.label_coal.setText(_translate("MainWindow", "煤种"))
        self.finishButton.setText(_translate("MainWindow", "生成参数表"))
        self.weight_label.setText(_translate("MainWindow", "吨位"))
        self.label_ticket.setText(_translate("MainWindow", "票种"))
        self.user_name_label.setText(_translate("MainWindow", "客户姓名"))
        self.car_id_label.setText(_translate("MainWindow", "车号"))
        self.pushButton.setText(_translate("MainWindow", "确定添加"))
        self.edit.setTitle(_translate("MainWindow", "编辑"))
        self.menuhelp.setTitle(_translate("MainWindow", "Help"))
        self.coal.setTitle(_translate("MainWindow", "煤种"))
        self.ticket.setTitle(_translate("MainWindow", "票种"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.manage_ticket.setText(_translate("MainWindow", "添加票种"))
        self.manage_ticket.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.query_ticket_info.setText(_translate("MainWindow", "查询票种"))
        self.query_ticket_info.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.coalManagement.setText(_translate("MainWindow", "煤种管理"))

