# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(820, 480, 101, 21))
        self.exit.setObjectName("exit")
        self.coal_sorts = QtWidgets.QComboBox(self.centralwidget)
        self.coal_sorts.setGeometry(QtCore.QRect(80, 280, 131, 21))
        self.coal_sorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.coal_sorts.setObjectName("coal_sorts")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setGeometry(QtCore.QRect(10, 80, 59, 16))
        self.date_label.setObjectName("date_label")
        self.label_coal = QtWidgets.QLabel(self.centralwidget)
        self.label_coal.setGeometry(QtCore.QRect(10, 280, 59, 16))
        self.label_coal.setObjectName("label_coal")
        self.finishButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishButton.setGeometry(QtCore.QRect(700, 480, 101, 21))
        self.finishButton.setObjectName("finishButton")
        self.date_calender = QtWidgets.QCalendarWidget(self.centralwidget)
        self.date_calender.setGeometry(QtCore.QRect(80, 20, 296, 151))
        self.date_calender.setMinimumSize(QtCore.QSize(296, 0))
        self.date_calender.setObjectName("date_calender")
        self.weight_content = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.weight_content.setGeometry(QtCore.QRect(80, 320, 62, 22))
        self.weight_content.setObjectName("weight_content")
        self.weight_label = QtWidgets.QLabel(self.centralwidget)
        self.weight_label.setGeometry(QtCore.QRect(10, 330, 54, 12))
        self.weight_label.setObjectName("weight_label")
        self.ticket_sorts = QtWidgets.QComboBox(self.centralwidget)
        self.ticket_sorts.setGeometry(QtCore.QRect(80, 370, 131, 21))
        self.ticket_sorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.ticket_sorts.setObjectName("ticket_sorts")
        self.label_ticket = QtWidgets.QLabel(self.centralwidget)
        self.label_ticket.setGeometry(QtCore.QRect(10, 370, 59, 16))
        self.label_ticket.setObjectName("label_ticket")
        self.user_name_label = QtWidgets.QLabel(self.centralwidget)
        self.user_name_label.setGeometry(QtCore.QRect(10, 200, 54, 12))
        self.user_name_label.setObjectName("user_name_label")
        self.user_name_content = QtWidgets.QTextEdit(self.centralwidget)
        self.user_name_content.setGeometry(QtCore.QRect(80, 200, 101, 21))
        self.user_name_content.setObjectName("user_name_content")
        self.car_id_label = QtWidgets.QLabel(self.centralwidget)
        self.car_id_label.setGeometry(QtCore.QRect(10, 240, 54, 16))
        self.car_id_label.setObjectName("car_id_label")
        self.car_id_content = QtWidgets.QTextEdit(self.centralwidget)
        self.car_id_content.setGeometry(QtCore.QRect(80, 240, 101, 21))
        self.car_id_content.setObjectName("car_id_content")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(570, 210, 351, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.operation_record_label = QtWidgets.QLabel(self.centralwidget)
        self.operation_record_label.setGeometry(QtCore.QRect(500, 40, 54, 12))
        self.operation_record_label.setObjectName("operation_record_label")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(620, 20, 301, 161))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 410, 491, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 471, 81))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(190, 20, 91, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(100, 20, 91, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 110, 471, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_ticket_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_ticket_2.setGeometry(QtCore.QRect(60, 30, 59, 16))
        self.label_ticket_2.setObjectName("label_ticket_2")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit.setGeometry(QtCore.QRect(110, 30, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_ticket_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_ticket_3.setGeometry(QtCore.QRect(240, 30, 59, 16))
        self.label_ticket_3.setObjectName("label_ticket_3")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_2.setGeometry(QtCore.QRect(300, 30, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 23))
        self.menubar.setObjectName("menubar")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        self.coal = QtWidgets.QMenu(self.menubar)
        self.coal.setObjectName("coal")
        self.ticket = QtWidgets.QMenu(self.menubar)
        self.ticket.setObjectName("ticket")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.manage_ticket = QtWidgets.QAction(MainWindow)
        self.manage_ticket.setCheckable(True)
        self.manage_ticket.setObjectName("manage_ticket")
        self.query_ticket_info = QtWidgets.QAction(MainWindow)
        self.query_ticket_info.setObjectName("query_ticket_info")
        self.coalManagement = QtWidgets.QAction(MainWindow)
        self.coalManagement.setObjectName("coalManagement")
        self.compute_by_person = QtWidgets.QAction(MainWindow)
        self.compute_by_person.setObjectName("compute_by_person")
        self.compute_by_coal = QtWidgets.QAction(MainWindow)
        self.compute_by_coal.setObjectName("compute_by_coal")
        self.compute_by_ticket = QtWidgets.QAction(MainWindow)
        self.compute_by_ticket.setObjectName("compute_by_ticket")
        self.menuhelp.addAction(self.compute_by_person)
        self.menuhelp.addAction(self.compute_by_coal)
        self.menuhelp.addAction(self.compute_by_ticket)
        self.coal.addAction(self.coalManagement)
        self.ticket.addAction(self.manage_ticket)
        self.ticket.addAction(self.query_ticket_info)
        self.menubar.addAction(self.coal.menuAction())
        self.menubar.addAction(self.ticket.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.coal_sorts.currentIndexChanged['int'].connect(MainWindow.onCoalSortSelected)
        self.exit.clicked.connect(MainWindow.exit)
        self.date_calender.clicked['QDate'].connect(MainWindow.beginDate)
        self.finishButton.clicked.connect(MainWindow.onAddFinished)
        self.manage_ticket.triggered.connect(MainWindow.manage_ticket)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.date_label.setText(_translate("MainWindow", "登记日期"))
        self.label_coal.setText(_translate("MainWindow", "煤种"))
        self.finishButton.setText(_translate("MainWindow", "计算"))
        self.weight_label.setText(_translate("MainWindow", "吨位"))
        self.label_ticket.setText(_translate("MainWindow", "票种"))
        self.user_name_label.setText(_translate("MainWindow", "客户姓名"))
        self.car_id_label.setText(_translate("MainWindow", "车号"))
        self.pushButton.setText(_translate("MainWindow", "添加"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">粗体用b表示。</span> </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">斜体用i表示。</span> </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">芙蓉姐姐这个词当中划线表示删除。 </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">想唱就唱这个词下划线插入。 </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">X<span style=\" vertical-align:sub;\">2</span>其中的2是下标 </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">X<span style=\" vertical-align:super;\">2</span>其中的2是上标 </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:40px; margin-right:40px; -qt-block-indent:0; text-indent:0px;\">好好学习，天天向上。这句话缩进表示引用 </p>\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">这是  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">预设(preformatted)文本.  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">在pre这个tag里的文本      保留  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">空格和  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">分行。   call getOrders </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">用code显示计算机代码，code里显示的字符是等宽字符。 </p></body></html>"))
        self.operation_record_label.setText(_translate("MainWindow", "操作记录"))
        self.groupBox_2.setTitle(_translate("MainWindow", "计算选项"))
        self.groupBox.setTitle(_translate("MainWindow", "计算种类"))
        self.checkBox_3.setText(_translate("MainWindow", "按煤种计算"))
        self.checkBox.setText(_translate("MainWindow", "按人计算"))
        self.checkBox_2.setText(_translate("MainWindow", "按票种计算"))
        self.groupBox_3.setTitle(_translate("MainWindow", "日期选择"))
        self.label_ticket_2.setText(_translate("MainWindow", "起始日期"))
        self.label_ticket_3.setText(_translate("MainWindow", "截止日期"))
        self.menuhelp.setTitle(_translate("MainWindow", "计算方式"))
        self.coal.setTitle(_translate("MainWindow", "煤种管理"))
        self.ticket.setTitle(_translate("MainWindow", "票种管理"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.manage_ticket.setText(_translate("MainWindow", "添加票种"))
        self.manage_ticket.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.query_ticket_info.setText(_translate("MainWindow", "查询票种"))
        self.query_ticket_info.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.coalManagement.setText(_translate("MainWindow", "煤种管理"))
        self.compute_by_person.setText(_translate("MainWindow", "按人计算"))
        self.compute_by_coal.setText(_translate("MainWindow", "按煤种计算"))
        self.compute_by_coal.setToolTip(_translate("MainWindow", "支持按照煤种类查找"))
        self.compute_by_ticket.setText(_translate("MainWindow", "按票种计算"))
        self.compute_by_ticket.setToolTip(_translate("MainWindow", "支持按照票种类进行计算"))

