# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1343, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(120, 430, 101, 21))
        self.exit.setObjectName("exit")
        self.coal_sorts = QtWidgets.QComboBox(self.centralwidget)
        self.coal_sorts.setGeometry(QtCore.QRect(110, 130, 131, 21))
        self.coal_sorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.coal_sorts.setObjectName("coal_sorts")
        self.label_coal = QtWidgets.QLabel(self.centralwidget)
        self.label_coal.setGeometry(QtCore.QRect(40, 130, 59, 16))
        self.label_coal.setObjectName("label_coal")
        self.add_record_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_record_btn.setGeometry(QtCore.QRect(110, 250, 101, 21))
        self.add_record_btn.setObjectName("add_record_btn")
        self.weight_label = QtWidgets.QLabel(self.centralwidget)
        self.weight_label.setGeometry(QtCore.QRect(40, 170, 54, 12))
        self.weight_label.setObjectName("weight_label")
        self.ticket_sorts = QtWidgets.QComboBox(self.centralwidget)
        self.ticket_sorts.setGeometry(QtCore.QRect(110, 200, 131, 21))
        self.ticket_sorts.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.ticket_sorts.setObjectName("ticket_sorts")
        self.label_ticket = QtWidgets.QLabel(self.centralwidget)
        self.label_ticket.setGeometry(QtCore.QRect(40, 200, 59, 16))
        self.label_ticket.setObjectName("label_ticket")
        self.user_name_label = QtWidgets.QLabel(self.centralwidget)
        self.user_name_label.setGeometry(QtCore.QRect(30, 60, 54, 12))
        self.user_name_label.setObjectName("user_name_label")
        self.car_id_label = QtWidgets.QLabel(self.centralwidget)
        self.car_id_label.setGeometry(QtCore.QRect(40, 90, 54, 16))
        self.car_id_label.setObjectName("car_id_label")
        self.select_date_btn = QtWidgets.QPushButton(self.centralwidget)
        self.select_date_btn.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.select_date_btn.setObjectName("select_date_btn")
        self.date_value_display = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.date_value_display.setGeometry(QtCore.QRect(110, 20, 151, 21))
        self.date_value_display.setObjectName("date_value_display")
        self.usernmae_content = QtWidgets.QLineEdit(self.centralwidget)
        self.usernmae_content.setGeometry(QtCore.QRect(110, 60, 151, 20))
        self.usernmae_content.setObjectName("usernmae_content")
        self.car_id_content = QtWidgets.QLineEdit(self.centralwidget)
        self.car_id_content.setGeometry(QtCore.QRect(110, 90, 151, 20))
        self.car_id_content.setObjectName("car_id_content")
        self.weight_value = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.weight_value.setGeometry(QtCore.QRect(110, 170, 62, 22))
        self.weight_value.setObjectName("weight_value")
        self.ticket_price_display = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ticket_price_display.setGeometry(QtCore.QRect(260, 200, 151, 21))
        self.ticket_price_display.setObjectName("ticket_price_display")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1343, 23))
        self.menubar.setObjectName("menubar")
        self.menu_acount = QtWidgets.QMenu(self.menubar)
        self.menu_acount.setObjectName("menu_acount")
        self.coal = QtWidgets.QMenu(self.menubar)
        self.coal.setObjectName("coal")
        self.menu_5 = QtWidgets.QMenu(self.coal)
        self.menu_5.setObjectName("menu_5")
        self.ticket = QtWidgets.QMenu(self.menubar)
        self.ticket.setObjectName("ticket")
        self.menu_2 = QtWidgets.QMenu(self.ticket)
        self.menu_2.setObjectName("menu_2")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.add_new_ticket = QtWidgets.QAction(MainWindow)
        self.add_new_ticket.setCheckable(True)
        self.add_new_ticket.setObjectName("add_new_ticket")
        self.query_ticket_info = QtWidgets.QAction(MainWindow)
        self.query_ticket_info.setObjectName("query_ticket_info")
        self.add_new_coal = QtWidgets.QAction(MainWindow)
        self.add_new_coal.setObjectName("add_new_coal")
        self.compute_account = QtWidgets.QAction(MainWindow)
        self.compute_account.setObjectName("compute_account")
        self.history_acount = QtWidgets.QAction(MainWindow)
        self.history_acount.setObjectName("history_acount")
        self.compute_by_ticket = QtWidgets.QAction(MainWindow)
        self.compute_by_ticket.setObjectName("compute_by_ticket")
        self.ticket_purchase_price_management = QtWidgets.QAction(MainWindow)
        self.ticket_purchase_price_management.setObjectName("ticket_purchase_price_management")
        self.sell_price_management = QtWidgets.QAction(MainWindow)
        self.sell_price_management.setObjectName("sell_price_management")
        self.coal_purchase_price_manag = QtWidgets.QAction(MainWindow)
        self.coal_purchase_price_manag.setObjectName("coal_purchase_price_manag")
        self.coal_sell_price_management = QtWidgets.QAction(MainWindow)
        self.coal_sell_price_management.setObjectName("coal_sell_price_management")
        self.menu_acount.addAction(self.compute_account)
        self.menu_acount.addAction(self.history_acount)
        self.menu_5.addAction(self.coal_purchase_price_manag)
        self.menu_5.addAction(self.coal_sell_price_management)
        self.coal.addAction(self.menu_5.menuAction())
        self.coal.addAction(self.add_new_coal)
        self.menu_2.addAction(self.ticket_purchase_price_management)
        self.menu_2.addAction(self.sell_price_management)
        self.ticket.addAction(self.menu_2.menuAction())
        self.ticket.addAction(self.add_new_ticket)
        self.ticket.addAction(self.query_ticket_info)
        self.menubar.addAction(self.coal.menuAction())
        self.menubar.addAction(self.ticket.menuAction())
        self.menubar.addAction(self.menu_acount.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.coal_sorts.currentIndexChanged['int'].connect(MainWindow.onCoalSortSelected)
        self.exit.clicked.connect(MainWindow.exit)
        self.add_record_btn.clicked.connect(MainWindow.on_record_add)
        self.add_new_ticket.triggered.connect(MainWindow.on_add_new_ticket)
        self.select_date_btn.clicked.connect(MainWindow.on_date_selected)
        self.usernmae_content.editingFinished.connect(MainWindow.on_name_input)
        self.car_id_content.editingFinished.connect(MainWindow.on_input_car_id)
        self.weight_value.editingFinished.connect(MainWindow.on_weight_value_input)
        self.ticket_sorts.currentIndexChanged['int'].connect(MainWindow.on_ticket_selected)
        self.add_new_coal.triggered.connect(MainWindow.on_add_new_coal)
        self.compute_account.triggered.connect(MainWindow.on_compute_account)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.label_coal.setText(_translate("MainWindow", "煤种"))
        self.add_record_btn.setText(_translate("MainWindow", "添加记录"))
        self.weight_label.setText(_translate("MainWindow", "吨位"))
        self.label_ticket.setText(_translate("MainWindow", "票种"))
        self.user_name_label.setText(_translate("MainWindow", "客户姓名"))
        self.car_id_label.setText(_translate("MainWindow", "车号"))
        self.select_date_btn.setText(_translate("MainWindow", "选择日期"))
        self.menu_acount.setTitle(_translate("MainWindow", "账单"))
        self.coal.setTitle(_translate("MainWindow", "煤种管理"))
        self.menu_5.setTitle(_translate("MainWindow", "煤价管理"))
        self.ticket.setTitle(_translate("MainWindow", "票种管理"))
        self.menu_2.setTitle(_translate("MainWindow", "票价管理"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.menu_3.setTitle(_translate("MainWindow", "操作明细"))
        self.menu_4.setTitle(_translate("MainWindow", "导入文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.add_new_ticket.setText(_translate("MainWindow", "添加票种"))
        self.add_new_ticket.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.query_ticket_info.setText(_translate("MainWindow", "查询票种"))
        self.query_ticket_info.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.add_new_coal.setText(_translate("MainWindow", "添加煤种"))
        self.compute_account.setText(_translate("MainWindow", "出账"))
        self.history_acount.setText(_translate("MainWindow", "历史账单"))
        self.history_acount.setToolTip(_translate("MainWindow", "支持按照煤种类查找"))
        self.compute_by_ticket.setText(_translate("MainWindow", "按票种计算"))
        self.compute_by_ticket.setToolTip(_translate("MainWindow", "支持按照票种类进行计算"))
        self.ticket_purchase_price_management.setText(_translate("MainWindow", "进价管理"))
        self.sell_price_management.setText(_translate("MainWindow", "售价管理"))
        self.coal_purchase_price_manag.setText(_translate("MainWindow", "进价管理"))
        self.coal_sell_price_management.setText(_translate("MainWindow", "售价管理"))

